export const UPDATE_MCQS="UPDATE_MCQS";
export const UPDATE_FILLS="UPDATE_FILLS";
export const UPDATE_MCQ_MARKS="UPDATE_MCQ_MARKS";
export const UPDATE_FILL_MARKS="UPDATE_FILL_MARKS";
export const UPDATE_CODE_MARKS="UPDATE_CODE_MARKS"